### ISSUE TITLE
New Artifact Idea

### ISSUE THREAD

**Issue by EnderGrimm1** [cheeeeeeeeeen/RoR2-ChensBombasticMod#1]
Artifact of Cluster

Explosions have a chance to spawn bombs. (Yes it can self proc)

**Comment by cheeeeeeeeeen** [comment]
I'm not sure if this is possible. The bombs heavily depend on the spawner's damage. Clustering it would lose track of the original.

Another problem is that turning it on by itself (without the bomb artifacts) won't do anything.

**Comment by cheeeeeeeeeen** [comment]
I will consider this if you thought of a revision that can be implemented into the game.

__It needs to work on its own without being dependent on other artifacts.__

**Comment by EnderGrimm1** [comment]
Well its more so a bomb would spawn whenever an explosion is triggered such as an item trigger such as Will O Wisp, Behemoth, etc, Pots would trigger it, enemy attacks like a Jellyfish explosion, Void Reaver Death, Overloading Elites bomb attack, etc etc etc

**Comment by EnderGrimm1** [comment]
If need be ill try and find all default game things that have some form of explosion

**Comment by cheeeeeeeeeen** [comment]
I'm not very convinced yet. I'm thinking still of a way to make it happen.

**Comment by cheeeeeeeeeen** [comment]
Moved to Discussions #5. Closed for now; will be re-opened once the idea becomes official.
