### ISSUE TITLE
Bombastic Mod Hard Limit Request

### ISSUE THREAD

**Issue by dmubiodit** [cheeeeeeeeeen/RoR2-ChensBombasticMod#8]
### Is your feature request related to a problem? Please describe.
-The sheer number of bombs from the spleen artifact (Enemies have a chance to generate bombs upon being attacked), caused my game to continuously crash on stage 6.

### Describe the solution you'd like
-I would like if it was possible there could be a hard limit on the number of the bombs that may appear at any given time (similar to how the vanilla Forgive Me Please + Soulbound Catalyst was patched a few updates ago). Or if there can be a config file that can let the user choose how many bombs they want to allow at once.

### Describe alternatives you've considered
-Unsure of any alternatives.

**Comment by cheeeeeeeeeen** [comment]
For now, decrease the chance. It should indirectly help with your endeavor
until I make an option.

**Comment by cheeeeeeeeeen** [comment]
Implemented.
